# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroLogApp', '0002_auto_20160414_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='qualiffication',
            new_name='qualification',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
