# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroLogApp', '0003_auto_20160414_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalexams',
            name='data',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='patients',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
