# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroLogApp', '0005_auto_20160414_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='birth_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='last_name',
            field=models.CharField(db_index=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='photo',
            field=models.BinaryField(null=True),
        ),
    ]
