# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuroLogApp', '0006_auto_20160421_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
